language: java
jdk:
  - openjdk11


stages:
  - build
  - test
  - deploy

build:
  stage: build
  script: ./gradlew clean build

test:
  stage: test
  script: ./gradlew clean test

deploy:
  provider: heroku
  api_key: 8359be78-57e7-43b6-b2c5-74c6ecc6e620
  app: rsoi-l1

notifications:
  email: false